# Generated by Django 5.2.12 on 2026-03-23 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0002_remove_missingperson_identification_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('station_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='missingperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingperson',
            name='report_type',
            field=models.CharField(choices=[('POLICE', 'Police'), ('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='aadhar_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Surveillance Camera', max_length=200)),
                ('confidence', models.FloatField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missingperson.missingperson')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
